sudo: false
language: ruby
cache:
  - bundler
  - directories:
    - $HOME/.m2
rvm:
  - jruby-19mode
before_install:
  - bundle install
  - rake compile
  - curl -s -o kafka.tgz $(curl -s https://www.apache.org/dyn/closer.cgi?path=/kafka/0.8.2.2/kafka_2.10-0.8.2.2.tgz | grep -o '<strong>[^<]*</strong>'|sed 's/<[^>]*>//g'|head -1)
  - mkdir kafka && tar xzf kafka.tgz -C kafka --strip-components 1
  - kafka/bin/zookeeper-server-start.sh kafka/config/zookeeper.properties &
  - kafka/bin/kafka-server-start.sh kafka/config/server.properties &
  - sleep 10
  - kafka/bin/kafka-topics.sh --create --partitions 1 --replication-factor 1 --topic test --zookeeper localhost:2181
  - kafka/bin/kafka-topics.sh --create --partitions 1 --replication-factor 1 --topic apple --zookeeper localhost:2181
  - kafka/bin/kafka-topics.sh --create --partitions 1 --replication-factor 1 --topic cabin --zookeeper localhost:2181
  - kafka/bin/kafka-topics.sh --create --partitions 1 --replication-factor 1 --topic carburetor --zookeeper localhost:2181
